"""empty message

Revision ID: 3a56925b6873
Revises: 8983ca58c5bc
Create Date: 2022-05-18 10:34:57.648349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a56925b6873'
down_revision = '8983ca58c5bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
